#!/usr/bin/env bash

# Check if pipenv is installed
if ! command -v pipenv &> /dev/null; then
    echo "pipenv not found. Installing pipenv..."
    pip install --user pipenv
    # Add the user base's bin directory to PATH
    export PATH="$PATH:$(python3 -m site --user-base)/bin"
fi

# Attempt to get the virtual environment path
pipenv --venv > /dev/null 2>&1

export PIPENV_VERBOSITY=-1

# If pipenv --venv failed, it means no virtual environment exists
if [ $? -ne 0 ]; then
    echo "First time around - Setting up pipenv environment..."
    pipenv sync > /dev/null 2>&1
fi

pipenv run python $(dirname "$0")/gh_semver.py "$@"
