# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  workflow_dispatch:
  push:
#    branches: 
#      - "main"
    paths:
      - ".github/workflows/python-app.yml"
  pull_request:
    branches: [ "main" ]


permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        git config --global user.email "testrunnter@github.com"
        git config --global user.name "testrunner"
        pip install pipenv
        pipenv sync --dev

    - name: Test with pytest
      run: |
        pipenv run pytest --cov=. -m dev

    - name: Generate coverage report
      run: |
        pipenv run coverage html

    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: htmlcov/
